In [38]:
%pip install scikit-learn



Note: you may need to restart the kernel to use updated packages.


In [39]:
from sklearn.linear_model import LinearRegression
import pandas as pd

In [40]:
#y = mx+mx+b    ne kadar feautre o kadar mx

In [41]:
df=pd.read_csv("Student_Marks.csv")

In [42]:
df.head(3)

number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811

In [43]:
#y= a1x + a2x + b

In [44]:
y=df[["Marks"]]
x=df[["number_courses", "time_study"]]

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    int64  
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [46]:
lm=LinearRegression()      # sklearn.Linear_model.LinearRegression()
model=lm.fit(x,y) #train

In [47]:
X_new=pd.DataFrame([[4,7]], columns=["number_courses", "time_study"])
model.predict(X_new)  #prediction

array([[37.79410825]])

In [48]:
df["Marks"].max()

np.float64(55.299)

In [49]:
model.score(x,y)

0.9403656320238896

In [50]:
df.columns=["sinif", "saat", "puan"]

In [51]:
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [52]:
y=df[["puan"]]
x=df[["sinif", "saat"]]

In [53]:
lm=LinearRegression()

In [54]:
model=lm.fit(x,y) 

In [55]:
model.score(x,y)

0.9403656320238896

In [56]:
model.coef_  #a1x + a2x   => a1 and a2 coefficients

array([[1.86405074, 5.39917879]])

In [57]:
model.intercept_ #b constant

array([-7.45634623])

In [58]:
X_new=pd.DataFrame([[4,5]], columns=["sinif","saat"])
model.predict(X_new)  #prediction

array([[26.99575068]])

In [59]:
(4*1.86405074)+(5*5.39917879) + (-7.45634623)

26.99575068

In [60]:
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [61]:
X_new = pd.DataFrame([[4, 4.508]], columns=["sinif","saat"])

s1=model.predict(X_new)[0][0]

In [62]:
-(19.202-s1)/19.202    #deviation

np.float64(0.2675426889853267)

In [63]:
model.score(x,y)   #accuracy

0.9403656320238896